# Generated by Django 5.0.6 on 2024-05-22 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToDo',
        ),
    ]
