# Generated by Django 5.0.6 on 2024-05-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('add', '0002_delete_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_name', models.CharField(max_length=50)),
                ('priority_level', models.DecimalField(decimal_places=0, max_digits=10)),
                ('is_finish', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
